### ISSUE TITLE
The documentation link is dead.

### ISSUE THREAD

**Issue by ChALkeR** [dropbox/dropbox-js#216]
Atm the documentation link (http://coffeedoc.info/github/dropbox/dropbox-js/master/class_index.html) shows an error page saying:
>400
>www.coffeedoc.info is currently stopped

There is no other online documentation for this library.

**Comment by smarx** [comment]
See also https://github.com/coffeedoc/coffeedoc.info/issues/9.

**Comment by davidmerfield** [comment]
In the meantime the old docs are [accessible on the wayback machine](https://web.archive.org/web/20131213035158/http://coffeedoc.info/github/dropbox/dropbox-js/master/class_index.html).

**Comment by pwnall** [comment]
@davidmerfield Do you happen to know any other Codo documentation hosting service? 

@smarx Should I host the files in my Dropbox?

**Comment by aseemk** [comment]
@pwnall: I'm facing this too (https://github.com/thingdom/node-neo4j/issues/148). :smile:

I've been thinking of a couple of options:

- Simply check in the generated docs and expose via `gh-pages`.

- Manually write the documentation as Markdown files checked into the repo. I always felt that the iframed Codo viewer wasn't very user-friendly anyway. (E.g. as you navigate, the browser URL doesn't change, so sharing a particular link with someone involves manual work, and then that link doesn't have the outer navigational iframes.)

- Simply take the coffeedoc.info repo and spin up a new instance on Nodejitsu or Heroku just for the library's docs. One instance on Heroku is free (don't know about Nodejitsu). The only downside is a custom domain would cost $$.

**Comment by pwnall** [comment]
@aseemk I thought of heroku before. Unfortunately, coffeedoc.info seems to use 2 drones, which would translate into 2 dynos. I'm sure the drones can be merged, and so far I've been put off by the prospect of doing this on my own.

I can do a first pass at getting coffeedoc.info working on heroku, if you'd be willing to code-review and help me with whatever ongoing maintenance work pops up.

**Comment by aseemk** [comment]
Ah ok, good to know.

I don't think I can commit to helping out w/ that effort right now, sorry! Have my hands more than full at work at the moment (big things spinning up that I can't talk about yet... :smile:).

In that case, I'd consider going the `gh-pages` route. Can be manual updates for now, but may not be too hard to set up a git commit hook that auto-updates it down the road.

**Comment by aseemk** [comment]
I gave the latest Codo a stab today locally on the new code I'm writing, and unfortunately, I'm running into issues there too:

https://github.com/coffeedoc/codo/issues/194
https://github.com/coffeedoc/codo/issues/195

Given those issues, I'm leaning towards simply writing manual Markdown documentation instead, and just checking it into the repo under a `docs/` directory. GitHub renders it well enough I suppose...

**Comment by smarx** [comment]
@pwnall Do you have a copy of the docs anywhere? (Or are you able to get them to generate?) If so, I can host them somewhere. But I'm unable to get "cake doc" to actually build the docs.

**Comment by pwnall** [comment]
@smarx I got an error as well, seems like bitrot got to it. I'll try to fix the problem this weekend.

**Comment by aseemk** [comment]
It looks like coffeedoc.info is back! https://github.com/coffeedoc/coffeedoc.info/issues/9

**Comment by pwnall** [comment]
@aseemk Thanks for the great news!
