### ISSUE TITLE
unable to call Dropbox.Client.getDatastoreManager

### ISSUE THREAD

**Issue by anuragpeshne** [dropbox/dropbox-js#218]
I have successfully authenticated `Dropbox.Client` object and I'm able to call all the methods on it except when I call `getDatastoreManager` then it throws an error 
> TypeError: Object #<Client> has no method 'getDatastoreManager'

I'm using node v0.10.31. Is accessing Datastore possible using this library?

**Comment by smarx** [comment]
If you're using the code from this repo, then no. You'll want https://www.dropbox.com/developers/datastore/sdks/js, which is a fork of this library that adds datastore functionality.

**Comment by anuragpeshne** [comment]
it worked. Thanks.
