### ISSUE TITLE
This repo, datastore-js or core API?

### ISSUE THREAD

**Issue by lexar** [dropbox/dropbox-js#225]
Hello,
I would like to use Dropbox to sync a small text file with Dropbox in a hybrid mobile app. This is the first time I am using the Dropbox API. Reading the deprecation note I am confused which repo, if any, I should use:
-datastore-js is deprecated, but seems to be the one to choose for syncing? 
-this repository is unofficial, but from Dropbox? Is this library able to sync files automatically and notify the client?
-then there is core API (https://www.dropbox.com/developers/core), but no official javascript support
-finally, there is API v2 in development (https://blogs.dropbox.com/developers/2015/04/a-preview-of-the-new-dropbox-api-v2/) in the apparently near future, how much would I have to refactor to support it?

So which way should I go for this task: Read, update and sync a text file within a hybrid app?
I am sorry if this is off-topic, but it's difficult to google because the deprecation is so young and the terms dropbox, sync, api etc. have way too many unrelated results :)
Any help appreciated!

**Comment by smarx** [comment]
* This repository has nothing to do with the Datastore API.
* This library is the closest there is to an official JavaScript library from Dropbox. (It was written by a Dropbox intern, and he continues to maintain it, but we host it under the Dropbox GitHub organization.)
* API v2 will likely have a JavaScript SDK in the future. For now I would just use v1 (with this library).

If you're reading and writing text files, this SDK should work fine for you.

**Comment by lexar** [comment]
Great, thanks!
