### ISSUE TITLE
All files and folders

### ISSUE THREAD

**Issue by ogdans3** [dropbox/dropbox-js#230]
Is there a way to get all files and folders that the user has in their dropbox? Without using recursive requests, this quickly reaches becomes thousands of requests

**Comment by rodri042** [comment]
```coffee-script
Dropbox = require("dropbox")
Promise = require("bluebird")
_ = require("lodash")

module.exports =

class DropboxApi
	constructor: (token) ->
		@client = Promise.promisifyAll new Dropbox.Client { token }

	readDir: (tail = { changes: [] }) =>
		@client.deltaAsync(tail.cursorTag)
			.catch (e) => throw "Error reading the remote directory /."
			.then (delta) =>
				delta.changes = tail.changes.concat delta.changes

				if delta.shouldPullAgain
					@readDir delta
				else delta
```

Usage:
```coffee-script
new DropboxApi("A token").readDir().then (entries) =>
  console.log entries
```

**Comment by sdkcarlos** [comment]
@rodri042 Can you be more explicit with your example ? The file dropbox.js doesn't seems to have the DropboxApi class :+1:

**Comment by rodri042** [comment]
It is a coffeescript class created by me, and the readDir method does the job. If you dont use coffee, you can go to coffee-script.org and compile the code online.

**Comment by sdkcarlos** [comment]
@ogdans3 I just read the documentation and the following code did the trick for me 

```javascript
var path = '/';
client.readdir(path, function(error, entries,dir,data) {
               
                if (error) {
                    return showError(error);  // Something went wrong.
                }
 
                console.log(data); /// See all the folders and files in the path
                data.forEach(function(seeObjectOfEveryItemFolderOrFile){
                    console.log(seeObjectOfEveryItemFolderOrFile);
                });

                html += '</ul>';
            });
```
You can manage your own listings, thanks for your answer @rodri042

**Comment by ogdans3** [comment]
Heres what i ended up doing:
This gets ALL the files and folders within someones dropbox account.

    var get_all_files_and_folders = function(list, cursor, errors, cb){
        client.pullChanges(cursor, function(error, t){
            list = list.concat(t.changes)
            errors.push(error)
            if(t.shouldPullAgain && !t.shouldBackOff){
               get_all_files_and_folders(list, t.cursorTag, errors, cb)
            }else{
               if(cb){
                   cb(errors, list)
               }
            }
        })
    }
    
    get_all_files_and_folders([], null, [], function(errors, changes){
        //To get the stat of an answer do this, x is some element: 
        var stat = changes[x].stat
    })

@sdkcarlos Yours will only get the files within that particular path, and only one level deep, right? 
The code above should get all files and folders within a dropbox account.
