### ISSUE TITLE
Writing binary images with a base64 string

### ISSUE THREAD

**Issue by pketh** [dropbox/dropbox-js#235]
so in my node app I've got a base64 string representation of a png

e.g. 
`b64image = data:image/png;base64,iVBORw0KGgoAA...`

I'm trying to save it using 

```
dropbox.writeFile('img.png', b64image, function(error, stat) {
});
```

That produced a corrupt png

I've also tried converting the string to a buffer before giving it to the dropbox lib with 

`drawingBuffer = new Buffer(drawing, 'base64')`

but passing drawingBuffer still led to a corrupt png? 

Do you know what I'm doing wrong, or how to generally get a base64 image string onto dropbox as an actual image file?

Thanks!

**Comment by smarx** [comment]
If you're passing that whole string into the `Buffer` constructor, I would expect that to fail (since it's not valid base 64). You should pass just the base 64 part... e.g. something like `b64image.substring(b64image.indexOf('base64,')+7)`.

**Comment by pketh** [comment]
@smarx that worked great, Thanks!
