### ISSUE TITLE
Status code 403 issued under certain circumstances

### ISSUE THREAD

**Issue by jvilk** [dropbox/dropbox-js#237]
This may be more of a documentation error.

The [documentation](http://coffeedoc.info/github/dropbox/dropbox-js/master/classes/Dropbox/ApiError.html) states the following for status code 403:

> OAUTH_ERROR =
> Status value indicating a malformed OAuth request.
> This indicates a bug in dropbox.js and should never occur under normal circumstances.

However, 403 is used in other scenarios, where the OAuth request is not malformed, but the request fails. For example, here are some error messages that accompany status code 403:

* You cannot move a folder into itself (via `Client.move`)
* A file with that name already exists (via `Client.move` to move a file over an existing file)

Is this intentional on the server side?

For now, I guess I'm going to need to programmatically grep error messages to figure out the context (eek! :frowning: ).

**Comment by smarx** [comment]
You might want to search for "403" in the documentation to see where it can be returned: https://www.dropbox.com/developers-v1/core/docs.

Sorry about needing to grep error messages. API v2 always returns specific errors you can reliably test for, but there's unfortunately no JavaScript SDK available yet.

**Comment by jvilk** [comment]
Thanks. That helps!
