### ISSUE TITLE
Can this library be used to create a new folder?

### ISSUE THREAD

**Issue by pketh** [dropbox/dropbox-js#239]
I've searched the docs, and looked through the lib itself and don't see any methods for creating a new folder. The dropbox api has an `create_folder` endpoint, but I couldn't find anything like that in here.

Also, I've tried simply creating new files in a new path, hoping that it would create any necessary folders if they didn't already exist. Doing this:

```    
dropbox.writeFile path, drawing, (error, stat) ->
      if error
        console.log error
      else
        console.log stat
```

returns a success stat object that looks like: 

```
Stat {
  _json: 
   { revision: 92,
     bytes: 4446,
     thumb_exists: true,
     rev: '5c3c5ddbb1',
     modified: 'Wed, 28 Oct 2015 00:28:30 +0000',
     mime_type: 'image/png',
     path: '/2015-44/459d8fc4-2f73-4ba2-be06-eda828ff8990.png',
     is_dir: false,
     size: '4.3 KB',
     root: 'app_folder',
     client_mtime: 'Wed, 28 Oct 2015 00:28:30 +0000',
     icon: 'page_white_picture' },
  path: '/2015-44/459d8fc4-2f73-4ba2-be06-eda828ff8990.png',
  name: '459d8fc4-2f73-4ba2-be06-eda828ff8990.png',
  isFolder: false,
  isFile: true,
  isRemoved: false,
  typeIcon: 'page_white_picture',
  modifiedAt: Tue Oct 27 2015 17:28:30 GMT-0700 (PDT),
  clientModifiedAt: Tue Oct 27 2015 17:28:30 GMT-0700 (PDT),
  inAppFolder: true,
  size: 4446,
  humanSize: '4.3 KB',
  hasThumbnail: true,
  versionTag: '5c3c5ddbb1',
  contentHash: null,
  mimeType: 'image/png' }

```

but the file and folder do not exist in my dropbox folder?

Any help is appreciated - thanks!

**Comment by smarx** [comment]
I think `mkdir` is what you're looking for. (I searched the code for "create_folder" to find this.)

But yes, there's no need to create the folder if you're about to write files into it. The folder will be implicitly created. It looks like the file is being written from your example.

Why do you say the file and folder don't exist? Are you sure you're looking in the right account and the right location? (E.g. if you have an "app folder" permission app, the folder you created will be in `~/Dropbox/Apps/<your app name>/2015-44`.)

**Comment by pketh** [comment]
hmm you're right, the files were being created but my dropbox app crashed and things weren't being synced 

_slaps forehead_

thx :)
