### ISSUE TITLE
Cordova dropbox chooser

### ISSUE THREAD

**Issue by sdkcarlos** [dropbox/dropbox-js#241]
I want to use the following Dropbox javascript function https://www.dropbox.com/developers/chooser#javascript

The authentication already worked according to this issue : https://github.com/dropbox/dropbox-js/issues/106#issuecomment-22827628 , i'm using cordova. When executing 

```javascript
Dropbox.choose(options);
```

A page with the response : 

```json
{"error":"Invalid Origin"}
```
Is received. Any idea why this is happening ?

**Comment by smarx** [comment]
The code here is unrelated to the Dropbox Chooser, so this isn't a good forum to ask for help. See https://www.dropbox.com/developers/support for better options.
