### ISSUE TITLE
Dropbox.Client is not a function

### ISSUE THREAD

**Issue by merhawifissehaye** [dropbox/dropbox-js#250]
I launched node, imported dropbox as `var Dropbox = require('dropbox')`
and then when I run code to create a new instance of `Dropbox.Client` with key and secret, it gives me the following error:
```
TypeError: Dropbox.Client is not a function
    at repl:1:14
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
```

**Comment by rqhub** [comment]
Same here

**Comment by jdibling** [comment]
As little as I want to be that guy who says "I'm having that problem as well," I am too. When I tried to look further into it and creating a client (As it said in the initialazion section) it instructed me to create the dropbox client using the following link:

http://coffeedoc.info/github/dropbox/dropbox-js/master/classes/Dropbox/Client.html

However, the server is down and the domain is lost, as stated by the devs: 

https://github.com/coffeedoc/coffeedoc.info#the-website

I don't know how to work around this and I may just be overlooking something completely. Hopefully this at least helps lead someone to a solution!

**Comment by braincore** [comment]
Any chance you all can try out our new SDK? https://github.com/dropbox/dropbox-sdk-js

**Comment by rqhub** [comment]
works.
Thx

**Comment by jdibling** [comment]
Perfect, thank you so much!

**Comment by merhawifissehaye** [comment]
Perfect.

**Comment by braincore** [comment]
@RileyTomasek I think we need to make it clearer that the new awesome SDK is out :)

**Comment by ranthonissen** [comment]
It is awesome, but it doesn't support download and upload yet. Which makes it it useless in lots of cases.
So don't forget to mention that little detail too :)

**Comment by rqhub** [comment]
Yups. Wondering if db is loosing momentum.
