### ISSUE TITLE
Dropbox api(NodeJS) filesDownload issue

### ISSUE THREAD

**Issue by Manan007224** [dropbox/dropbox-js#257]
hi, I am exploring the dropbox api and trying to write the code for downloading files from Dropbox into a local path using nodejs. Seeing the documentation it only tells me to provide the path of the file in dropbox in the args object. Does anyone know where to provide the local path.

**Comment by greg-db** [comment]
There's an example using of a download-style call in Node here:

https://github.com/dropbox/dropbox-sdk-js/blob/master/examples/javascript/node/download.js#L19

You don't directly supply a local file path for the resulting file data in the SDK method argument. Instead, the callback gives you the file data, which you can use as desired. (E.g., save it to a file using `fs.writeFile`, as shown in this example.)
