### ISSUE TITLE
Dropbox chooser returns relative links instead of absolute in link property

### ISSUE THREAD

**Issue by vikdet** [dropbox/dropbox-js#259]
Hi! We are using the Chooser (https://www.dropbox.com/developers/chooser) with the following settings 
```
Dropbox.choose({
     linkType: 'preview',
     ...
})
```
and it worked well so far. 
The selected file had .link property similar to *https://www.dropbox.com/s/kfo5w0500ieprfe/%5B%20jpg.jpg?dl=0*. But now the link is relative like: "/Photos/IMG_4199.JPG". And that breaks our application.

**Comment by greg-db** [comment]
Thanks for the report. We're working on it. 

By the way, please note that this "dropbox-js" library is unrelated to the Dropbox Chooser. It also uses the retired API v1, and so is also retired and unsupported. For future reference, you can report Dropbox developer platform issues here: https://www.dropbox.com/developers/contact

**Comment by greg-db** [comment]
This should be fixed now. Apologies for the trouble!

**Comment by vikdet** [comment]
@greg-db Thanks 👍 ! To be honest i didn't find where to report this issue and leave it just here.
